// Dev tool — rasterize a PNG into half-block terminal-art cells and emit a TS
// data module (so the runtime/binary needs no image decoder, just the data).
//
//   bun run scripts/png-to-terminal-art.ts <png> <out.ts> <EXPORT_NAME> [cols]
//
// Each output cell is a ▀ with foreground = the top source pixel and background
// = the bottom one (two pixels per character row); transparent pixels are left
// blank. Colour is alpha-weighted so transparent edges don't darken the art.
import { readFileSync, writeFileSync } from "node:fs";
import { PNG } from "pngjs";

const [, , input, outPath, exportName, colsArg] = process.argv;
if (!input || !outPath || !exportName) {
  console.error("usage: bun run scripts/png-to-terminal-art.ts <png> <out.ts> <EXPORT_NAME> [cols]");
  process.exit(1);
}
const targetCols = Number(colsArg ?? 26);

const png = PNG.sync.read(readFileSync(input));
const { width, height, data } = png;
const px = (x: number, y: number): [number, number, number, number] => {
  const i = (y * width + x) * 4;
  return [data[i] ?? 0, data[i + 1] ?? 0, data[i + 2] ?? 0, data[i + 3] ?? 0];
};

// Bounding box of non-transparent pixels (trim the transparent margin).
let minX = width;
let minY = height;
let maxX = 0;
let maxY = 0;
for (let y = 0; y < height; y++) {
  for (let x = 0; x < width; x++) {
    if (px(x, y)[3] > 16) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
}
const bw = maxX - minX + 1;
const bh = maxY - minY + 1;

// Output grid: targetCols wide, aspect-preserved (half-block packs 2 px/row).
const pxW = targetCols;
const pxH = Math.max(2, Math.round((pxW * bh) / bw));

// Box-average the source region mapping to output pixel (ox, oy); colour is
// alpha-weighted, alpha is the plain mean (so edge cells fade out).
const sample = (ox: number, oy: number): [number, number, number, number] | null => {
  const sx0 = minX + Math.floor((ox * bw) / pxW);
  const sx1 = Math.max(minX + Math.floor(((ox + 1) * bw) / pxW), sx0 + 1);
  const sy0 = minY + Math.floor((oy * bh) / pxH);
  const sy1 = Math.max(minY + Math.floor(((oy + 1) * bh) / pxH), sy0 + 1);
  let r = 0;
  let g = 0;
  let b = 0;
  let aw = 0;
  let asum = 0;
  let n = 0;
  for (let y = sy0; y < sy1 && y < height; y++) {
    for (let x = sx0; x < sx1 && x < width; x++) {
      const [pr, pg, pb, pa] = px(x, y);
      r += pr * pa;
      g += pg * pa;
      b += pb * pa;
      aw += pa;
      asum += pa;
      n++;
    }
  }
  if (n === 0 || aw === 0) return null;
  return [Math.round(r / aw), Math.round(g / aw), Math.round(b / aw), Math.round(asum / n)];
};

const hex = (c: [number, number, number, number]): string =>
  `#${c[0].toString(16).padStart(2, "0")}${c[1].toString(16).padStart(2, "0")}${c[2]
    .toString(16)
    .padStart(2, "0")}`;

const VISIBLE = 80; // alpha threshold below which a sub-pixel is "transparent"
type Cell = { char: string; color?: string; bg?: string };
const rows: Cell[][] = [];
for (let cy = 0; cy < pxH; cy += 2) {
  const cells: Cell[] = [];
  for (let cx = 0; cx < pxW; cx++) {
    const top = sample(cx, cy);
    const bot = cy + 1 < pxH ? sample(cx, cy + 1) : null;
    const topVis = top !== null && top[3] >= VISIBLE;
    const botVis = bot !== null && bot[3] >= VISIBLE;
    if (topVis && top && botVis && bot) cells.push({ char: "▀", color: hex(top), bg: hex(bot) });
    else if (topVis && top) cells.push({ char: "▀", color: hex(top) });
    else if (botVis && bot) cells.push({ char: "▄", color: hex(bot) });
    else cells.push({ char: " " });
  }
  rows.push(cells);
}

writeFileSync(
  outPath,
  `// GENERATED by scripts/png-to-terminal-art.ts from ${input} — do not edit by hand.\n` +
    `import type { ArtCell } from "@shared/ui/brand/art.ts";\n\n` +
    `export const ${exportName}: ArtCell[][] = ${JSON.stringify(rows)};\n`,
);
console.log(`wrote ${outPath}: ${rows.length} rows × ${pxW} cols (from ${bw}x${bh} bbox)`);
