// Session, coding, board and model commands. Flags are transcribed from each
// command's own parseFlags spec; anything not listed there is not listed here.
import type { CommandSpec } from "@app/config/commandSpec.ts";

export const CORE_COMMANDS: readonly CommandSpec[] = [
  {
    name: "chat",
    group: "session",
    summary: "interactive chat with the agent (default)",
    usage: ["regent", "regent chat"],
    examples: ["regent"],
    seeAlso: ["sessions", "code"],
  },
  {
    name: "ask",
    group: "session",
    summary: "ask one question, get an answer, exit — for scripts and pipes",
    usage: ['regent ask "<question>"', "… | regent ask"],
    flags: [
      { name: "continue", alias: "c", type: "boolean", doc: "continue the last session" },
      { name: "json", type: "boolean", doc: "one JSON object instead of prose" },
      { name: "yes", type: "boolean", doc: "allow gated actions instead of denying them" },
      { name: "timeout", type: "string", doc: "give up after N seconds" },
      { name: "events", type: "boolean", doc: "NDJSON event stream on stdout (automation)" },
      { name: "session", type: "string", doc: "continue a specific session id (automation)" },
    ],
    examples: [
      'regent ask "what changed in this repo today"',
      'echo "summarise this" | regent ask',
      'regent ask "list the open PRs" --json',
    ],
    seeAlso: ["chat", "code"],
  },
  {
    name: "sessions",
    group: "session",
    summary: "list | search | resume past sessions",
    needsDeacon: true,
    subcommands: [
      ["list", "recent sessions, newest first"],
      ["search <text>", "find a session by its content"],
      ["resume <id>", "reopen one in the chat surface"],
    ],
    flags: [{ name: "limit", type: "string", doc: "how many to list" }],
    examples: ["regent sessions list --limit 20", "regent sessions resume abc123"],
  },
  {
    name: "memory",
    group: "session",
    summary: "pending | approve | reject | list | pin | unpin | forget",
    needsDeacon: true,
    subcommands: [
      ["pending", "memories waiting for review"],
      ["approve <id>", "keep a pending memory"],
      ["reject <id>", "discard a pending memory"],
      ["list", "everything remembered"],
      ["pin <id>", "keep a memory from ever being pruned"],
      ["unpin <id>", "undo a pin"],
      ["forget <id>", "delete a memory"],
    ],
    examples: ["regent memory pending", "regent memory approve 12"],
  },
  {
    name: "status",
    group: "session",
    summary: "deacon health / model / cron snapshot",
    needsDeacon: true,
    seeAlso: ["doctor"],
  },
  {
    name: "code",
    group: "coding",
    summary: 'plan-mode coding: regent code "<task>" → plan → verify → revert',
    usage: ['regent code "<task>"', "regent code settings [auto on|off]"],
    flags: [{ name: "yes", type: "boolean", doc: "approve the plan without asking" }],
    examples: ['regent code "add a --json flag to doctor"', "regent code settings auto on"],
    seeAlso: ["auto"],
  },
  {
    name: "auto",
    group: "coding",
    summary: "run the coding harness without the plan gate",
    seeAlso: ["code"],
  },
  {
    name: "kanban",
    group: "board",
    summary: "list | create | show | assign | start | review | block | unblock | complete",
    needsDeacon: true,
    examples: ["regent kanban list"],
  },
  {
    name: "agents",
    group: "board",
    summary: "list | create | show | edit | remove named agents (kanban assignees)",
    needsDeacon: true,
    flags: [
      { name: "description", alias: "d", type: "string", doc: "what the agent is for" },
      { name: "prompt", type: "string", doc: "its system prompt" },
      { name: "model", alias: "m", type: "string", doc: "model to run it on" },
      { name: "tools", alias: "t", type: "string", doc: "comma-separated tool allowlist" },
    ],
    examples: ['regent agents create reviewer -d "reviews PRs" -m claude-opus-5'],
    seeAlso: ["mom", "kanban"],
  },
  {
    name: "mom",
    group: "board",
    summary: "Mixture-of-Models groups: several models propose, one aggregates",
    usage: [
      "regent mom list",
      "regent mom create <name> --proposers a,b --aggregator c",
      'regent mom run <name> "<brief>"',
    ],
    flags: [
      { name: "proposers", alias: "p", type: "string", doc: "comma-separated proposer models" },
      { name: "aggregator", alias: "a", type: "string", doc: "model that merges the proposals" },
      { name: "max", type: "string", doc: "cap on proposers actually run" },
    ],
    examples: ['regent mom run research "compare these two designs"'],
  },
  {
    name: "model",
    group: "model",
    summary: "show · list · set <id>",
    needsDeacon: true,
    subcommands: [
      ["list", "every model the configured providers offer"],
      ["set <id>", "switch the active model"],
    ],
    examples: ["regent model list", "regent model set claude-opus-5"],
    seeAlso: ["providers", "keys"],
  },
  {
    name: "providers",
    group: "model",
    summary: "list · add · remove · test model providers",
    subcommands: [
      ["list", "configured providers"],
      ["add <name>", "add one (edits config.yaml, no deacon needed)"],
      ["remove <name>", "drop one"],
      ["test", "check each provider answers"],
    ],
    flags: [
      { name: "kind", alias: "k", type: "string", doc: "provider kind (anthropic, openai, …)" },
      { name: "base-url", type: "string", doc: "override the endpoint" },
      { name: "key-env", type: "string", doc: "env var holding the API key" },
      { name: "models", alias: "m", type: "string", doc: "comma-separated model ids" },
    ],
    examples: ["regent providers add groq -k groq --key-env GROQ_API_KEY"],
  },
  {
    name: "skills",
    group: "model",
    summary: "list · view · create · opt-out",
    needsDeacon: true,
    flags: [
      { name: "description", type: "string", doc: "what the skill is for" },
      { name: "body", type: "string", doc: "the skill text" },
      { name: "file", type: "string", doc: "read the body from a file instead" },
    ],
    examples: ["regent skills list", "regent skills create deploy --file ./deploy.md"],
  },
  {
    name: "tools",
    group: "model",
    summary: "list · enable | disable <tool>",
    subcommands: [
      ["list", "every tool in the session catalog"],
      ["enable <tool>", "turn one back on"],
      ["disable <tool>", "keep one out of the catalog"],
    ],
    examples: ["regent tools list", "regent tools disable web_search"],
  },
];
