// Config, gateway, voice and operations commands. Flags are transcribed from
// each command's own parseFlags spec; anything not listed there is not here.
import type { CommandSpec } from "@app/config/commandSpec.ts";

export const OPS_COMMANDS: readonly CommandSpec[] = [
  {
    name: "config",
    group: "config",
    summary: "show · list · set <key> <value> · unset <key> · validate",
    subcommands: [
      ["list", "keys you have changed (--all for every key, --json for scripts)"],
      ["set <key> <value>", "change one, validated against the real schema first"],
      ["unset <key>", "remove one — the repair for a typo'd key"],
      ["validate", "check config.yaml, with or without a running deacon"],
    ],
    examples: [
      "regent config set model.default claude-opus-5",
      'regent config set tools.deferred \'["calc","weather"]\'',
      "regent config unset model.defalut",
      "regent config validate",
    ],
    seeAlso: ["doctor", "security"],
  },
  {
    name: "profile",
    group: "config",
    summary: "list · create · delete profile homes",
    flags: [{ name: "force", type: "boolean", doc: "delete without confirmation" }],
    examples: ["regent profile list", "regent -p work status"],
  },
  {
    name: "setup",
    group: "config",
    summary: "first-time configuration (provider, model, key)",
    flags: [
      { name: "provider", type: "string", doc: "provider name" },
      { name: "model", type: "string", doc: "default model id" },
      { name: "base-url", type: "string", doc: "override the endpoint" },
      {
        name: "key-stdin",
        type: "boolean",
        doc: "read the API key from stdin (never command history)",
      },
    ],
    examples: ["regent setup --provider anthropic --model claude-sonnet-4-6"],
  },
  {
    name: "update",
    group: "config",
    summary: "show the deacon's cached official release status",
    flags: [{ name: "check", type: "boolean", doc: "explicit status alias" }],
    examples: ["regent update", "regent update --check"],
    seeAlso: ["doctor", "version"],
    needsDeacon: true,
  },
  {
    name: "migrate",
    group: "config",
    summary: "import a Hermes/OpenClaw install (dry-run; --apply to write)",
    flags: [
      { name: "home", type: "string", doc: "the install to import from" },
      { name: "apply", type: "boolean", doc: "actually write (default is a dry run)" },
    ],
    examples: ["regent migrate --home ~/.hermes", "regent migrate --home ~/.hermes --apply"],
  },
  {
    name: "keys",
    group: "config",
    summary: "manage provider API keys (list · set · rm) in .env",
    examples: ["regent keys list", "regent keys set ANTHROPIC_API_KEY --stdin"],
    seeAlso: ["providers", "doctor"],
  },
  {
    name: "persona",
    group: "config",
    summary: "view persona + profile; list/create/switch persona profiles",
    needsDeacon: true,
    seeAlso: ["soul", "about"],
  },
  { name: "soul", group: "config", summary: "view/edit the agent persona", needsDeacon: true },
  { name: "about", group: "config", summary: "view/edit your user profile", needsDeacon: true },
  {
    name: "gateway",
    group: "gateway",
    summary: "setup <token> | start | stop | status | enable | disable",
    flags: [
      { name: "token", type: "string", doc: "platform bot token" },
      { name: "allow-all", type: "boolean", doc: "let anyone talk to the bot" },
      { name: "allowed-users", type: "string", doc: "comma-separated allowlist" },
      { name: "no-start", type: "boolean", doc: "configure without starting" },
    ],
    seeAlso: ["auth"],
  },
  { name: "auth", group: "gateway", summary: "status · revoke <user>" },
  {
    name: "voice",
    group: "voice",
    summary: "voice (ASR/TTS): setup, enable, status",
    flags: [
      { name: "provider", type: "string", doc: "speech provider" },
      { name: "asr-model", type: "string", doc: "speech-to-text model" },
      { name: "tts-model", type: "string", doc: "text-to-speech model" },
      { name: "base-url", type: "string", doc: "override the endpoint" },
      { name: "key", type: "string", doc: "API key for a hosted speech provider" },
      { name: "no-enable", type: "boolean", doc: "configure without turning voice on" },
    ],
    seeAlso: ["call"],
  },
  { name: "call", group: "voice", summary: "live real-time voice call (LiveKit Jarvis UI)" },
  {
    name: "cron",
    group: "ops",
    summary: "scheduled jobs: list · add · remove · pause · resume · run · edit",
    needsDeacon: true,
    flags: [
      { name: "name", type: "string", doc: "job name" },
      { name: "schedule", type: "string", doc: "when to run (e.g. 1d, 09:00)" },
      { name: "prompt", type: "string", doc: "what to do when it fires" },
    ],
    examples: ['regent cron add --name standup --schedule 1d --prompt "summarise yesterday"'],
    seeAlso: ["jobs"],
  },
  {
    name: "jobs",
    group: "ops",
    summary: "list background jobs · cancel <id> (stops at the job's next check)",
    needsDeacon: true,
    subcommands: [
      ["list", "running and recent background jobs"],
      ["cancel <id>", "ask one to stop at its next check"],
    ],
    seeAlso: ["cron"],
  },
  {
    name: "logs",
    group: "ops",
    summary: "show the deacon log",
    flags: [{ name: "follow", alias: "f", type: "boolean", doc: "keep printing new lines" }],
    examples: ["regent logs -f"],
  },
  {
    name: "doctor",
    group: "ops",
    summary: "check the installation",
    flags: [
      { name: "strict", type: "boolean", doc: "fail on warnings too, for CI" },
      { name: "json", type: "boolean", doc: "one JSON document instead of prose" },
    ],
    examples: ["regent doctor", "regent doctor --strict --json"],
    seeAlso: ["security", "config"],
  },
  {
    name: "security",
    group: "ops",
    summary: "report the security posture: approvals, sandbox, listener, hooks",
    flags: [{ name: "json", type: "boolean", doc: "stable JSON for scripts" }],
    examples: ["regent security", "regent security --json"],
    seeAlso: ["doctor"],
  },
  {
    name: "insights",
    group: "ops",
    summary: "usage rollup (turns, tokens, api calls)",
    needsDeacon: true,
  },
  {
    name: "completions",
    group: "ops",
    summary: "print a shell completion script (bash · zsh · fish · powershell)",
    usage: ["regent completions <bash|zsh|fish|powershell>"],
    examples: [
      "regent completions bash > /etc/bash_completion.d/regent",
      "regent completions powershell | Out-String | Invoke-Expression",
    ],
  },
  { name: "debug", group: "ops", summary: "redacted bug-report bundle" },
  { name: "mcp", group: "ops", summary: "serve Regent's tools over MCP (stdio)" },
  { name: "version", group: "ops", summary: "print the CLI version" },
];
