// `regent completions <bash|zsh|fish|powershell>` (plan C.4).
//
// Generated from COMMAND_SPECS, the same table `regent help` reads, so a
// completion can never offer a command that does not exist or miss one that
// does. PowerShell is included because Windows is this project's primary
// development host and omitting it was an oversight in the first draft.
//
// STATIC on purpose. A completion that starts a daemon, blocks on RPC, or prints
// a log line into the completion buffer is worse than no completion at all.
import { EXIT } from "@app/cli/exit.ts";
import { out, printError } from "@app/cli/runtime.ts";
import { COMMAND_SPECS } from "@app/config/commands.ts";

const SHELLS = ["bash", "zsh", "fish", "powershell"] as const;
type Shell = (typeof SHELLS)[number];

const names = () => COMMAND_SPECS.map((s) => s.name);

/** Long flags for one command, as the completion should offer them. */
function flagsFor(name: string): string[] {
  const spec = COMMAND_SPECS.find((s) => s.name === name);
  return (spec?.flags ?? []).map((f) => `--${f.name}`);
}

/** Subcommand words for one command. `<id>` placeholders are not completions. */
function subsFor(name: string): string[] {
  const spec = COMMAND_SPECS.find((s) => s.name === name);
  return (spec?.subcommands ?? []).map(([verb]) => (verb.split(" ")[0] as string) ?? "");
}

function bash(): string {
  const cases = COMMAND_SPECS.map((s) => {
    const words = [...subsFor(s.name), ...flagsFor(s.name)].join(" ");
    return words === "" ? null : `    ${s.name}) words="${words}" ;;`;
  }).filter(Boolean);
  return `# regent bash completion — generated by \`regent completions bash\`
_regent() {
  local cur prev words
  cur="\${COMP_WORDS[COMP_CWORD]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${names().join(" ")}" -- "$cur") )
    return
  fi
  case "\${COMP_WORDS[1]}" in
${cases.join("\n")}
    *) words="" ;;
  esac
  COMPREPLY=( $(compgen -W "$words" -- "$cur") )
}
complete -F _regent regent
`;
}

function zsh(): string {
  const lines = COMMAND_SPECS.map((s) => `    '${s.name}:${s.summary.replace(/'/g, "")}'`);
  const cases = COMMAND_SPECS.map((s) => {
    const words = [...subsFor(s.name), ...flagsFor(s.name)];
    return words.length === 0 ? null : `      ${s.name}) _values 'arg' ${words.join(" ")} ;;`;
  }).filter(Boolean);
  return `#compdef regent
# regent zsh completion — generated by \`regent completions zsh\`
_regent() {
  local -a subcmds
  subcmds=(
${lines.join("\n")}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' subcmds
    return
  fi
  case "\${words[2]}" in
${cases.join("\n")}
  esac
}
compdef _regent regent
`;
}

function fish(): string {
  const lines: string[] = [
    "# regent fish completion — generated by `regent completions fish`",
    "complete -c regent -f",
  ];
  for (const s of COMMAND_SPECS) {
    const desc = s.summary.replace(/'/g, "");
    lines.push(`complete -c regent -n __fish_use_subcommand -a ${s.name} -d '${desc}'`);
    for (const [verb, doc] of s.subcommands ?? []) {
      const word = (verb.split(" ")[0] as string) ?? "";
      lines.push(
        `complete -c regent -n "__fish_seen_subcommand_from ${s.name}" -a ${word} -d '${doc.replace(/'/g, "")}'`,
      );
    }
    for (const f of s.flags ?? []) {
      lines.push(
        `complete -c regent -n "__fish_seen_subcommand_from ${s.name}" -l ${f.name} -d '${f.doc.replace(/'/g, "")}'`,
      );
    }
  }
  return `${lines.join("\n")}\n`;
}

function powershell(): string {
  const cases = COMMAND_SPECS.map((s) => {
    const words = [...subsFor(s.name), ...flagsFor(s.name)];
    if (words.length === 0) return null;
    return `        '${s.name}' { @(${words.map((w) => `'${w}'`).join(", ")}) }`;
  }).filter(Boolean);
  return `# regent PowerShell completion — generated by \`regent completions powershell\`
# Add to your profile:  regent completions powershell | Out-String | Invoke-Expression
Register-ArgumentCompleter -Native -CommandName regent -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $words = $commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() }
    $candidates = if ($words.Count -le 1) {
        @(${names()
          .map((n) => `'${n}'`)
          .join(", ")})
    } else {
        switch ($words[0]) {
${cases.join("\n")}
            default { @() }
        }
    }
    $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}
`;
}

const GENERATORS: Record<Shell, () => string> = { bash, zsh, fish, powershell };

export function completionsCommand(args: string[]): number {
  const shell = args[0];
  if (!shell || !SHELLS.includes(shell as Shell)) {
    printError(`usage: regent completions <${SHELLS.join("|")}>`);
    return EXIT.usage;
  }
  out(GENERATORS[shell as Shell]());
  return EXIT.ok;
}
